name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  # allows manual trigger
  workflow_dispatch:

env:
  IMAGE_NAME: recruit-bot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Restart Docker Container
        run: |
          cat << EOF > run-container.sh
            #!/bin/bash
            
            IMAGE_ID=$(echo ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }})
            
            docker pull $IMAGE_ID:latest
            
            docker stop recruit-bot || true
            docker rm recruit-bot || true
            
            mkdir -p $(pwd)/data
            
            docker run -d --name recruit-bot --restart unless-stopped --env-file .env -v $(pwd)/data:/data -e SEEN_DB_PATH=/data/seen.db -e TZ=Asia/Seoul $IMAGE_ID:latest

            docker image prune -f
          EOF

          chmod +x ./run-container.sh

          ssh app-recrawler sh < ./run-container.sh
            

